import { Room } from '@/types';

export const sampleRooms: Room[] = [
  {
    id: '1',
    name: 'Studio Deluxe',
    type: 'studio',
    description: 'A cozy studio room perfect for solo travelers or couples. Features a comfortable 5x6 bed, Smart TV, and en-suite bathroom with hot water. Enjoy views of the lush Kirinyaga countryside.',
    bed_size: '5x6',
    has_smart_tv: true,
    has_kitchenette: false,
    has_ac: true,
    max_guests: 2,
    base_price: 3500.0000,
    is_available: true,
    image_url: '/images/rooms/studio-deluxe.png',
    floor_number: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Studio Premium',
    type: 'studio',
    description: 'Upgraded studio with extra space, a 6x6 bed, mini-fridge, and a work desk ideal for business travelers. Complimentary Starlink WiFi included.',
    bed_size: '6x6',
    has_smart_tv: true,
    has_kitchenette: false,
    has_ac: true,
    max_guests: 2,
    base_price: 4500.0000,
    is_available: true,
    image_url: '/images/rooms/studio-premium.png',
    floor_number: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Business Suite',
    type: 'business',
    description: 'Spacious business suite with a dedicated work area, 6x6 king bed, Smart TV, air conditioning, and en-suite kitchenette. Perfect for extended stays.',
    bed_size: '6x6',
    has_smart_tv: true,
    has_kitchenette: true,
    has_ac: true,
    max_guests: 2,
    base_price: 6500.0000,
    is_available: true,
    image_url: '/images/rooms/business-suite.png',
    floor_number: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Business Executive',
    type: 'business',
    description: 'Our premier business room featuring a separate living area, 6x6 bed, executive desk, Smart TV, full kitchenette, and premium Mt. Kenya views.',
    bed_size: '6x6',
    has_smart_tv: true,
    has_kitchenette: true,
    has_ac: true,
    max_guests: 3,
    base_price: 8500.0000,
    is_available: true,
    image_url: '/images/rooms/business-executive.png',
    floor_number: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Airbnb Garden View',
    type: 'airbnb',
    description: 'Self-contained unit with a private entrance, full kitchen, 5x6 bed, living area, and a private garden patio. Ideal for families or groups seeking independence.',
    bed_size: '5x6',
    has_smart_tv: true,
    has_kitchenette: true,
    has_ac: true,
    max_guests: 4,
    base_price: 5500.0000,
    is_available: true,
    image_url: '/images/rooms/airbnb-garden.png',
    floor_number: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Airbnb Family Suite',
    type: 'airbnb',
    description: 'Large two-bedroom self-contained unit with full kitchen, dining area, two bathrooms, Smart TVs in both rooms, and secure private parking. Perfect for families and Chamas.',
    bed_size: '6x6',
    has_smart_tv: true,
    has_kitchenette: true,
    has_ac: true,
    max_guests: 6,
    base_price: 9500.0000,
    is_available: true,
    image_url: '/images/rooms/airbnb-family.png',
    floor_number: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
